from pathlib import Path

MAIN=Path('web/src/main.js')
CSS=Path('web/src/styles.css')
PKG=Path('web/package.json')
s=MAIN.read_text(encoding='utf-8')

old="games:[],gameDetails:new Map,gameOpen:new Set,tradeA:null"
new="games:[],gameDetails:new Map,gameMarkets:new Map,gameOpen:new Set,tradeA:null"
if old not in s:
    raise SystemExit('state anchor missing')
s=s.replace(old,new,1)

old_live_load="""async function liveLoad(){const ns=await nflState(),data=await liveJson(`${ESPN}?dates=${ns?.season||st.season}&seasontype=2&week=${st.week}`,{});st.games=data?.events||[];const ids=new Set(st.games.map(e=>String(e.id)));for(const id of [...st.gameOpen])if(!ids.has(id))st.gameOpen.delete(id);render();const open=[...st.gameOpen];if(open.length)await Promise.all(open.map(id=>loadGameDetails(id,true)))}"""
new_live_load="""async function liveLoad(){const ns=await nflState(),data=await liveJson(`${ESPN}?dates=${ns?.season||st.season}&seasontype=2&week=${st.week}`,{});st.games=data?.events||[];const ids=new Set(st.games.map(e=>String(e.id)));for(const id of [...st.gameOpen])if(!ids.has(id))st.gameOpen.delete(id);for(const id of [...st.gameMarkets.keys()])if(!ids.has(id))st.gameMarkets.delete(id);render();await loadPregameMarkets(st.games);render();const open=[...st.gameOpen];if(open.length)await Promise.all(open.map(id=>loadGameDetails(id,true)))}"""
if old_live_load not in s:
    raise SystemExit('liveLoad anchor missing')
s=s.replace(old_live_load,new_live_load,1)

anchor="""function gameBox(e,a,h){const key=String(e.id),d=st.gameDetails.get(key);if(!st.gameOpen.has(key))return'';if(!d||d.loading)return'<div class=\"game-box-loading\">Loading box score…</div>';if(d.error)return'<div class=\"game-box-loading\">Box score is temporarily unavailable.</div>';const box=d.boxscore||{};return`<div class=\"game-box\">${gameTeamStats(box,a,h)}<div class=\"game-player-boxes\">${boxPlayerCategories(box,a)}${boxPlayerCategories(box,h)}</div></div>`}\n"""
insert=r'''function gameIsPregame(e,c=e?.competitions?.[0]||{}){const t=e?.status?.type||c?.status?.type||{},state=String(t?.state||'').toLowerCase(),name=String(t?.name||'').toUpperCase();if(t?.completed||state==='post'||state==='in'||name.includes('IN_PROGRESS')||name.includes('HALFTIME')||name.includes('FINAL'))return false;return state==='pre'||name.includes('SCHEDULED')||name.includes('CREATED')||!state}
function firstMarket(x){if(!x)return null;const candidates=[x?.odds,x?.pickcenter,x?.header?.competitions?.[0]?.odds,x?.header?.competitions?.[0]?.pickcenter,x?.gameInfo?.odds];for(const v of candidates){if(Array.isArray(v)&&v.length)return v[0];if(v&&typeof v==='object'&&!Array.isArray(v))return v}return null}
function marketMoneyline(o,home){const side=home?o?.homeTeamOdds:o?.awayTeamOdds;return maybeNum(side?.moneyLine??side?.moneyline??side?.money_line)}
function hasUsefulMarket(o){return !!o&&(o?.details!=null||maybeNum(o?.overUnder)!=null||marketMoneyline(o,true)!=null||marketMoneyline(o,false)!=null)}
function eventMarket(e,c=e?.competitions?.[0]||{}){return firstMarket(c)||st.gameMarkets.get(String(e?.id))?.market||null}
async function loadGameMarket(e){const key=String(e?.id||'');if(!key)return;const c=e?.competitions?.[0]||{},scoreboard=firstMarket(c),homeML=marketMoneyline(scoreboard,true),awayML=marketMoneyline(scoreboard,false);if(hasUsefulMarket(scoreboard)&&homeML!=null&&awayML!=null){st.gameMarkets.set(key,{market:scoreboard,source:'scoreboard'});return}st.gameMarkets.set(key,{...(st.gameMarkets.get(key)||{}),loading:true,market:scoreboard||null});const data=await liveJson(`${ESPN_SUMMARY}?event=${encodeURIComponent(key)}&enable=ranks,odds,linescores,logos`,null),market=firstMarket(data)||scoreboard||null,predictor=data?.predictor||data?.header?.competitions?.[0]?.predictor||null;st.gameMarkets.set(key,{loading:false,market,predictor,source:market&&market!==scoreboard?'summary':'scoreboard'})}
async function loadPregameMarkets(events){const tasks=[];for(const e of events||[]){const c=e?.competitions?.[0]||{};if(!gameIsPregame(e,c))continue;const o=firstMarket(c),homeML=marketMoneyline(o,true),awayML=marketMoneyline(o,false);if(hasUsefulMarket(o)&&homeML!=null&&awayML!=null){st.gameMarkets.set(String(e.id),{market:o,source:'scoreboard'});continue}tasks.push(loadGameMarket(e))}if(tasks.length)await Promise.all(tasks)}
function americanOdds(v){const x=maybeNum(v);return x==null?'—':x>0?`+${Math.round(x)}`:`${Math.round(x)}`}
function rawImplied(v){const x=maybeNum(v);if(x==null||x===0)return null;return x<0?(-x)/((-x)+100):100/(x+100)}
function predictorPct(v){const x=maybeNum(v);if(x==null)return null;return x<=1?x*100:x}
function marketProbabilities(o,predictor){const aML=marketMoneyline(o,false),hML=marketMoneyline(o,true),ar=rawImplied(aML),hr=rawImplied(hML);if(ar!=null&&hr!=null&&ar+hr>0)return{away:100*ar/(ar+hr),home:100*hr/(ar+hr),source:'Market implied'};const ap=predictorPct(predictor?.awayTeam?.gameProjection??predictor?.awayTeam?.winPercentage),hp=predictorPct(predictor?.homeTeam?.gameProjection??predictor?.homeTeam?.winPercentage);if(ap!=null&&hp!=null)return{away:ap,home:hp,source:'ESPN predictor'};return{away:null,home:null,source:''}}
function pregameMarket(e,c,a,h){if(!gameIsPregame(e,c))return'';const saved=st.gameMarkets.get(String(e.id))||{},o=eventMarket(e,c),provider=o?.provider?.name||o?.provider?.displayName||'',probs=marketProbabilities(o,saved.predictor),aML=marketMoneyline(o,false),hML=marketMoneyline(o,true),spread=o?.details||o?.spreadDisplayValue||null,total=maybeNum(o?.overUnder??o?.total);if(!o&&saved.loading)return'<div class="pregame-market loading"><div class="eyebrow">Pregame market</div><div class="muted small">Loading betting lines…</div></div>';if(!hasUsefulMarket(o)&&probs.away==null)return'<div class="pregame-market unavailable"><div class="eyebrow">Pregame market</div><div class="muted small">Betting lines are not currently available for this matchup.</div></div>';return`<div class="pregame-market"><div class="pregame-market-head"><div><div class="eyebrow">Pregame market</div><strong>${provider?esc(provider):'Current line'}</strong></div><div class="market-line-summary"><span>Spread <strong>${esc(spread??'—')}</strong></span><span>Total <strong>${total!=null?f(total,1):'—'}</strong></span></div></div><div class="market-teams"><div><span>${esc(a?.team?.abbreviation||'Away')}</span><strong>${americanOdds(aML)}</strong><small>Moneyline</small><b>${probs.away!=null?`${f(probs.away,1)}%`:'—'}</b><small>Win probability</small></div><div><span>${esc(h?.team?.abbreviation||'Home')}</span><strong>${americanOdds(hML)}</strong><small>Moneyline</small><b>${probs.home!=null?`${f(probs.home,1)}%`:'—'}</b><small>Win probability</small></div></div><div class="market-foot">${esc(probs.source||'Market data')}${probs.source==='Market implied'?' · normalized to remove the two-sided sportsbook vig':''} · lines can move before kickoff.</div></div>`}
'''
if anchor not in s:
    raise SystemExit('gameBox anchor missing')
s=s.replace(anchor,anchor+insert,1)

old_live=r'''function live(){const cards=st.games.map(e=>{const c=e.competitions?.[0]||{},ts=c.competitors||[],a=ts.find(x=>x.homeAway==='away')||{},h=ts.find(x=>x.homeAway==='home')||{},key=String(e.id),open=st.gameOpen.has(key),status=e.status?.type?.shortDetail||c.status?.type?.shortDetail||'Scheduled';return`<div class="card game-card ${open?'game-open':''}"><div class="game-status-row"><div class="game-status">${esc(status)}</div><div class="muted small">${esc(c.venue?.fullName||'')}</div></div><div class="game-score-team"><div>${gameTeamLogo(a)?`<img src="${gameTeamLogo(a)}" alt="">`:''}<span><strong>${esc(a.team?.abbreviation||'Away')}</strong><small>${esc(a.team?.displayName||'')}</small></span></div><strong>${esc(a.score||'0')}</strong></div><div class="game-score-team"><div>${gameTeamLogo(h)?`<img src="${gameTeamLogo(h)}" alt="">`:''}<span><strong>${esc(h.team?.abbreviation||'Home')}</strong><small>${esc(h.team?.displayName||'')}</small></span></div><strong>${esc(h.score||'0')}</strong></div>${(a.linescores?.length||h.linescores?.length)?`<div class="period-score"><div></div><div class="period-score-row">${periodScore(a)}</div><div class="period-score-row">${periodScore(h)}</div></div>`:''}<button class="game-box-toggle" data-game-toggle="${esc(key)}">${open?'Hide box score':'View box score'} <span>${open?'⌃':'⌄'}</span></button>${gameBox(e,a,h)}</div>`}).join('');return layout('Live NFL Stats',`<div class="toolbar"><div><h1 class="page-title">Live NFL Stats</h1><p class="page-subtitle">Live scores, team box stats and passing/rushing/receiving lines. Expand any game for the full fantasy-relevant box score.</p></div><div style="margin-left:auto">${weekSel()}</div><button class="btn" data-a="refreshLive">Refresh</button></div>${cards?`<div class="scoreboard">${cards}</div>`:'<div class="empty">Loading current NFL games…</div>'}`)}'''
new_live=r'''function live(){const cards=st.games.map(e=>{const c=e.competitions?.[0]||{},ts=c.competitors||[],a=ts.find(x=>x.homeAway==='away')||{},h=ts.find(x=>x.homeAway==='home')||{},key=String(e.id),open=st.gameOpen.has(key),status=e.status?.type?.shortDetail||c.status?.type?.shortDetail||'Scheduled',pregame=gameIsPregame(e,c);return`<div class="card game-card ${open?'game-open':''}"><div class="game-status-row"><div class="game-status">${esc(status)}</div><div class="muted small">${esc(c.venue?.fullName||'')}</div></div><div class="game-score-team"><div>${gameTeamLogo(a)?`<img src="${gameTeamLogo(a)}" alt="">`:''}<span><strong>${esc(a.team?.abbreviation||'Away')}</strong><small>${esc(a.team?.displayName||'')}</small></span></div><strong>${pregame?'—':esc(a.score||'0')}</strong></div><div class="game-score-team"><div>${gameTeamLogo(h)?`<img src="${gameTeamLogo(h)}" alt="">`:''}<span><strong>${esc(h.team?.abbreviation||'Home')}</strong><small>${esc(h.team?.displayName||'')}</small></span></div><strong>${pregame?'—':esc(h.score||'0')}</strong></div>${pregameMarket(e,c,a,h)}${(a.linescores?.length||h.linescores?.length)?`<div class="period-score"><div></div><div class="period-score-row">${periodScore(a)}</div><div class="period-score-row">${periodScore(h)}</div></div>`:''}<button class="game-box-toggle" data-game-toggle="${esc(key)}">${open?'Hide box score':'View box score'} <span>${open?'⌃':'⌄'}</span></button>${gameBox(e,a,h)}</div>`}).join('');return layout('Live NFL Stats',`<div class="toolbar"><div><h1 class="page-title">Live NFL Stats</h1><p class="page-subtitle">Live scores and box stats, plus spread, total, moneyline and win probability for games that have not kicked off.</p></div><div style="margin-left:auto">${weekSel()}</div><button class="btn" data-a="refreshLive">Refresh</button></div>${cards?`<div class="scoreboard">${cards}</div>`:'<div class="empty">Loading current NFL games…</div>'}`)}'''
if old_live not in s:
    raise SystemExit('live function anchor missing')
s=s.replace(old_live,new_live,1)
MAIN.write_text(s,encoding='utf-8')

css=CSS.read_text(encoding='utf-8')
css += r'''

/* Web 1.3.9 — pregame betting lines + market win probability */
.pregame-market{margin:12px 0 4px;padding:12px;border:1px solid rgba(182,255,69,.18);border-radius:12px;background:linear-gradient(135deg,rgba(182,255,69,.045),rgba(255,255,255,.012))}.pregame-market.loading,.pregame-market.unavailable{border-color:var(--line);background:rgba(255,255,255,.012)}.pregame-market-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.pregame-market-head>div:first-child>strong{font-size:12px}.market-line-summary{display:flex;gap:10px;flex-wrap:wrap;justify-content:flex-end}.market-line-summary span{font-size:10px;color:var(--muted);padding:5px 7px;border:1px solid rgba(36,51,43,.75);border-radius:7px}.market-line-summary strong{color:#e8f1eb;margin-left:3px}.market-teams{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.market-teams>div{display:grid;grid-template-columns:1fr auto;column-gap:8px;row-gap:2px;padding:9px 10px;border:1px solid rgba(36,51,43,.75);border-radius:9px;background:rgba(0,0,0,.08)}.market-teams span{grid-column:1/3;font-weight:850;font-size:12px}.market-teams strong,.market-teams b{font-size:15px}.market-teams small{color:var(--muted);font-size:9px;align-self:center}.market-teams b{color:var(--accent);text-align:right}.market-foot{margin-top:8px;color:var(--muted);font-size:9px;line-height:1.4}@media(max-width:520px){.pregame-market-head{display:block}.market-line-summary{justify-content:flex-start;margin-top:8px}.market-teams{grid-template-columns:1fr}}
'''
CSS.write_text(css,encoding='utf-8')

p=PKG.read_text(encoding='utf-8')
if '"version": "1.3.8"' not in p:
    raise SystemExit('expected Web 1.3.8')
p=p.replace('"version": "1.3.8"','"version": "1.3.9"',1)
PKG.write_text(p,encoding='utf-8')
print('Patched Web 1.3.9: pregame betting lines and win probability')
