from pathlib import Path
import re

MAIN=Path('web/src/main.js')
CSS=Path('web/src/styles.css')
PKG=Path('web/package.json')
s=MAIN.read_text(encoding='utf-8')

pattern=r"function moves\(\)\{.*?\}\nfunction leagueShell\(\)"
replacement=r'''function leagueRosteredIds(){return new Set(st.rosters.flatMap(r=>r.players||[]).map(String))}
function rosterCapacity(){return(st.league?.roster_positions||[]).filter(x=>!['IR','TAXI'].includes(String(x).toUpperCase())).length}
function activeRosterCount(r){const parked=new Set([...(r?.reserve||[]),...(r?.taxi||[])].map(String));return(r?.players||[]).filter(id=>!parked.has(String(id))).length}
function waiverDropCandidate(r){const actual=new Set((r?.starters||[]).filter(Boolean).map(String)),modeled=new Set([...optimal(r).keys()].map(String)),parked=new Set([...(r?.reserve||[]),...(r?.taxi||[])].map(String)),exact={};for(const x of slots()){const k=String(x).toUpperCase();if(['QB','RB','WR','TE','DEF','DST'].includes(k))exact[k]=(exact[k]||0)+1}const counts={};for(const id of r?.players||[]){const p=st.players?.[id],pos=String(p?.position||'').toUpperCase();counts[pos]=(counts[pos]||0)+1}return(r?.players||[]).filter(id=>!actual.has(String(id))&&!modeled.has(String(id))&&!parked.has(String(id))).map(id=>{const p=st.players?.[id]||{},m=model(id,p),pos=String(p.position||'').toUpperCase(),depthPenalty=(counts[pos]||0)<=((exact[pos]||0)+1)?500:0,keep=(m.projection||0)*100+(m.avg||0)*35+(m.dynasty||0)*.08+depthPenalty;return{id,p,m,keep}}).sort((a,b)=>a.keep-b.keep)[0]||null}
function waiverCandidates(r,limit=3){if(!r||!st.players)return[];const rostered=leagueRosteredIds(),capacity=rosterCapacity(),needsDrop=capacity>0&&activeRosterCount(r)>=capacity,drop=needsDrop?waiverDropCandidate(r):null;if(needsDrop&&!drop)return[];const baseProj=rproj(r),nd=need(r),dynastyLeague=+st.league?.settings?.type===2,allowed=new Set(['QB','RB','WR','TE','DEF','DST']),pool=[];for(const[id,p]of Object.entries(st.players)){if(rostered.has(String(id)))continue;const pos=String(p?.position||'').toUpperCase();if(!allowed.has(pos))continue;if(!p?.team&&!isDstId(id,p))continue;const m=model(id,p);if(m.availability?.forceZero)continue;if(m.projection==null&&m.avg==null&&!m.dynasty)continue;pool.push({id,p,m,pre:(m.projection||0)*100+(m.avg||0)*30+(m.dynasty||0)*.05+(pos===nd?75:0)})}pool.sort((a,b)=>b.pre-a.pre);const out=[];for(const x of pool.slice(0,80)){const dropId=drop?.id||null,testPlayers=(r.players||[]).filter(id=>String(id)!==String(dropId));testPlayers.push(x.id);const sim={...r,players:testPlayers},newProj=rproj(sim),weeklyGain=baseProj!=null&&newProj!=null?newProj-baseProj:0,dropDyn=drop?.m?.dynasty||0,dynastyGain=(x.m.dynasty||0)-dropDyn,dropAvg=drop?.m?.avg||0,seasonGain=(x.m.avg||0)-dropAvg,needMatch=String(x.p.position||'').toUpperCase()===nd,good=weeklyGain>=.6||(needMatch&&seasonGain>=1)||(dynastyLeague&&dynastyGain>=500);if(!good)continue;const score=weeklyGain*180+Math.max(-5,seasonGain)*20+(needMatch?60:0)+(dynastyLeague?dynastyGain*.035:0);out.push({...x,drop,weeklyGain,dynastyGain,seasonGain,needMatch,score,newProj})}return out.sort((a,b)=>b.score-a.score).slice(0,limit)}
function waiverReason(w){if(w.weeklyGain>=.6)return`Adding ${pname(w.id)} raises the modeled Week ${st.week} optimal lineup by ${f(w.weeklyGain)} points.`;if(+st.league?.settings?.type===2&&w.dynastyGain>=500)return`${pname(w.id)} adds ${fi(w.dynastyGain)} net dynasty-value points versus the suggested drop.`;return`${pname(w.id)} materially improves the current-season production profile at ${w.p.position}.`}
function waiverCards(a){if(!a.length)return'';return`<div class="section-head"><h2>Waiver opportunities</h2><span class="muted small">Only adds that clear the roster-improvement threshold are shown</span></div><div class="waiver-grid">${a.map((w,i)=>`<button class="waiver-card" data-player="${esc(w.id)}"><div class="waiver-rank">${i===0?'TOP ADD':`#${i+1}`}</div><div class="waiver-player"><img src="${assetImage(w.id,w.p)}" alt="" onerror="this.style.display='none'"><div><strong>${esc(pname(w.id))}</strong><span>${esc(w.p.position||'')} · ${esc(w.p.team||'FA')}</span></div></div><div class="waiver-metrics"><div><span>Week ${st.week}</span><strong>${f(w.m.projection)}</strong></div><div><span>Season PPG</span><strong>${f(w.m.avg)}</strong></div><div><span>Dynasty</span><strong>${w.m.dynasty!=null?fi(w.m.dynasty):'—'}</strong></div><div><span>Lineup gain</span><strong>${w.weeklyGain>0?`+${f(w.weeklyGain)}`:f(w.weeklyGain)}</strong></div></div><p>${esc(waiverReason(w))}</p><div class="waiver-drop">${w.drop?`Suggested drop: ${esc(pname(w.drop.id))}`:'Open roster spot · no drop required'}</div><div class="mobile-view-analysis">View player news + analysis</div></button>`).join('')}</div>`}
function moves(){const r=me();if(!r)return'<div class="empty">Connect a roster first.</div>';const nd=need(r),opt=optimal(r),cur=new Set(r.starters||[]),swap=[...opt.entries()].find(([id])=>!cur.has(id)),sur=['QB','RB','WR','TE'].map(p=>({p,c:(r.players||[]).filter(id=>st.players?.[id]?.position===p).length})).sort((a,b)=>b.c-a.c)[0],waivers=waiverCandidates(r,3),best=waivers[0],recs=[];if(best)recs.push([`Add ${pname(best.id)}`,waiverReason(best),best.drop?`Use a waiver claim/free-agent add for ${pname(best.id)} and consider dropping ${pname(best.drop.id)}.`:`Add ${pname(best.id)} into the open roster spot.`]);if(swap)recs.push([`Start ${pname(swap[0])}`,`The optimizer places this player in ${swap[1]}.`,'Review the Home tab before kickoff.']);recs.push([`Upgrade ${nd}`,`${nd} is your largest relative roster need.`,`Open Trade Center and target teams strong at ${nd}.`]);recs.push([`Shop surplus ${sur?.p||'depth'}`,`You carry ${sur?.c||0} ${sur?.p||''} assets, your deepest raw position group.`,'Use depth to address need before spending premium picks.']);return`<div class="eyebrow">Recommended Moves</div><h1 class="page-title">What should you do next?</h1><p class="page-subtitle">Prioritized GM actions from your roster, league context, projections, dynasty values and currently unrostered players.</p><div class="grid">${recs.map((x,i)=>`<div class="recommendation"><div class="rec-rank">#${i+1}</div><div class="rec-title">${esc(x[0])}</div><p class="muted">${esc(x[1])}</p><strong>Best path</strong><p>${esc(x[2])}</p></div>`).join('')}</div>${waiverCards(waivers)}<p class="muted small" style="margin-top:14px">Waiver suggestions use the league's current roster ownership, Fantasy Model weekly projections, current-season PPG, roster need and dynasty value. A player is only surfaced when the simulated add materially improves this roster. Availability on Sleeper can still depend on your league's waiver timing and claim rules.</p>`}
function leagueShell()'''
ns,count=re.subn(pattern,replacement,s,count=1,flags=re.S)
if count!=1:
    raise SystemExit(f'moves replacement count {count}')
MAIN.write_text(ns,encoding='utf-8')

css=CSS.read_text(encoding='utf-8')
css += r'''

/* Web 1.3.7 — waiver-aware Recommended Moves */
.waiver-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px}.waiver-card{display:block;width:100%;text-align:left;color:inherit;border:1px solid var(--line);border-radius:14px;background:linear-gradient(180deg,rgba(18,26,22,.98),rgba(13,19,16,.98));padding:14px;cursor:pointer}.waiver-card:hover{border-color:rgba(182,255,69,.34);transform:translateY(-1px)}.waiver-rank{color:var(--accent);font-size:10px;letter-spacing:.1em;font-weight:900}.waiver-player{display:flex;align-items:center;gap:10px;margin:8px 0 12px}.waiver-player img{width:46px;height:46px;border-radius:11px;object-fit:cover;object-position:center 15%;background:#17211c}.waiver-player>div{display:grid}.waiver-player span{color:var(--muted);font-size:11px;margin-top:2px}.waiver-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.waiver-metrics>div{padding:8px;border:1px solid rgba(36,51,43,.75);border-radius:9px;background:rgba(255,255,255,.015)}.waiver-metrics span{display:block;color:var(--muted);font-size:9px}.waiver-metrics strong{display:block;font-size:13px;margin-top:3px}.waiver-card p{font-size:12px;line-height:1.45;color:#dce8df}.waiver-drop{font-size:11px;color:var(--warn);font-weight:750}@media(max-width:600px){.waiver-grid{grid-template-columns:1fr}.waiver-metrics{grid-template-columns:repeat(2,1fr)}}
'''
CSS.write_text(css,encoding='utf-8')

p=PKG.read_text(encoding='utf-8')
if '"version": "1.3.6"' not in p:
    raise SystemExit('expected Web 1.3.6')
p=p.replace('"version": "1.3.6"','"version": "1.3.7"',1)
PKG.write_text(p,encoding='utf-8')
print('Patched Web 1.3.7: waiver-aware Recommended Moves')
