from pathlib import Path

MAIN=Path('web/src/main.js')
CSS=Path('web/src/styles.css')
PKG=Path('web/package.json')
s=MAIN.read_text(encoding='utf-8')

old_state="playerNews:new Map,games:[],tradeA:null"
new_state="playerNews:new Map,games:[],gameDetails:new Map,gameOpen:new Set,tradeA:null"
if old_state not in s: raise SystemExit('state anchor missing')
s=s.replace(old_state,new_state,1)

old_live="""async function liveLoad(){const ns=await nflState(),data=await json(`${ESPN}?dates=${ns?.season||st.season}&seasontype=2&week=${st.week}`,{});st.games=data?.events||[];render()}
function live(){const cards=st.games.map(e=>{const c=e.competitions?.[0]||{},ts=c.competitors||[],a=ts.find(x=>x.homeAway==='away')||{},h=ts.find(x=>x.homeAway==='home')||{};return`<div class=\"card game-card\"><div class=\"game-status\">${esc(e.status?.type?.shortDetail||'Scheduled')}</div><div class=\"game-line\"><span>${esc(a.team?.abbreviation||'Away')}</span><span>${esc(a.score||'0')}</span></div><div class=\"game-line\"><span>${esc(h.team?.abbreviation||'Home')}</span><span>${esc(h.score||'0')}</span></div><div class=\"muted small\">${esc(c.venue?.fullName||'')}</div></div>`}).join('');return layout('Live NFL Stats',`<div class=\"toolbar\"><div><h1 class=\"page-title\">Live NFL Stats</h1><p class=\"page-subtitle\">NFL scores and game status. No fantasy points.</p></div><div style=\"margin-left:auto\">${weekSel()}</div><button class=\"btn\" data-a=\"refreshLive\">Refresh</button></div>${cards?`<div class=\"scoreboard\">${cards}</div>`:'<div class=\"empty\">Loading current NFL games…</div>'}`)}
"""
new_live=r"""const ESPN_SUMMARY='https://site.api.espn.com/apis/site/v2/sports/football/nfl/summary';
async function loadGameDetails(id,force=false){const key=String(id);if(!force&&st.gameDetails.has(key)&&!st.gameDetails.get(key)?.error)return st.gameDetails.get(key);st.gameDetails.set(key,{loading:true});render();const data=await liveJson(`${ESPN_SUMMARY}?event=${encodeURIComponent(key)}`,null),value=data||{error:true};st.gameDetails.set(key,value);render();return value}
async function liveLoad(){const ns=await nflState(),data=await liveJson(`${ESPN}?dates=${ns?.season||st.season}&seasontype=2&week=${st.week}`,{});st.games=data?.events||[];const ids=new Set(st.games.map(e=>String(e.id)));for(const id of [...st.gameOpen])if(!ids.has(id))st.gameOpen.delete(id);render();const open=[...st.gameOpen];if(open.length)await Promise.all(open.map(id=>loadGameDetails(id,true)))}
function gameTeamLogo(x){return x?.team?.logo||x?.team?.logos?.[0]?.href||''}
function periodScore(x){const q=Array.isArray(x?.linescores)?x.linescores:[];return q.map((z,i)=>`<span><small>${i<4?`Q${i+1}`:`OT${i-3}`}</small><strong>${esc(z?.displayValue??z?.value??'—')}</strong></span>`).join('')}
function teamStatIndex(teamBox){const m=new Map;for(const x of teamBox?.statistics||[]){m.set(String(x?.name||'').toLowerCase(),x);m.set(normName(x?.label||x?.displayName||''),x)}return m}
function teamStatValue(teamBox,names){const m=teamStatIndex(teamBox);for(const k of names){const x=m.get(String(k).toLowerCase())||m.get(normName(k));if(x)return x.displayValue??x.value??'—'}return'—'}
function gameTeamStats(box,a,h){const teams=box?.teams||[],find=x=>teams.find(t=>String(t?.team?.id)===String(x?.team?.id))||teams.find(t=>String(t?.team?.abbreviation||'').toUpperCase()===String(x?.team?.abbreviation||'').toUpperCase()),ab=find(a),hb=find(h),rows=[['First downs',['firstDowns','1st Downs']],['Total yards',['totalYards','Total Yards']],['Passing yards',['netPassingYards','passingYards','Passing Yards']],['Rushing yards',['rushingYards','Rushing Yards']],['Third down',['thirdDownEff','3rd Down Efficiency']],['Turnovers',['turnovers','Turnovers']],['Penalties',['totalPenaltiesYards','Penalties']],['Possession',['possessionTime','Possession Time']]];if(!ab&&!hb)return'';return`<div class="game-section"><div class="game-section-title">Team stats</div><div class="game-team-stats"><div class="game-stat-head"><span>${esc(a?.team?.abbreviation||'Away')}</span><span>STAT</span><span>${esc(h?.team?.abbreviation||'Home')}</span></div>${rows.map(([label,keys])=>`<div class="game-stat-row"><strong>${esc(teamStatValue(ab,keys))}</strong><span>${esc(label)}</span><strong>${esc(teamStatValue(hb,keys))}</strong></div>`).join('')}</div></div>`}
function boxPlayerCategories(box,competitor){const teamId=String(competitor?.team?.id||''),abbr=String(competitor?.team?.abbreviation||''),entry=(box?.players||[]).find(x=>String(x?.team?.id||'')===teamId)||(box?.players||[]).find(x=>String(x?.team?.abbreviation||'').toUpperCase()===abbr.toUpperCase());if(!entry)return'';const wanted=new Set(['passing','rushing','receiving']),cats=(entry.statistics||[]).filter(g=>wanted.has(String(g?.name||'').toLowerCase())||wanted.has(String(g?.displayName||'').toLowerCase()));if(!cats.length)return'';return`<div class="game-team-box"><div class="game-team-box-title">${gameTeamLogo(competitor)?`<img src="${gameTeamLogo(competitor)}" alt="">`:''}<strong>${esc(competitor?.team?.displayName||abbr)}</strong></div>${cats.map(g=>{const labels=g.labels||g.keys||[],ath=g.athletes||[];if(!ath.length)return'';return`<div class="box-category"><div class="box-category-title">${esc(g.displayName||g.name||'Stats')}</div><div class="box-table-wrap"><table class="box-table"><thead><tr><th>Player</th>${labels.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${ath.map(x=>`<tr><td>${esc(x?.athlete?.shortName||x?.athlete?.displayName||'Player')}</td>${(x?.stats||[]).map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`}).join('')}</div>`}
function gameBox(e,a,h){const key=String(e.id),d=st.gameDetails.get(key);if(!st.gameOpen.has(key))return'';if(!d||d.loading)return'<div class="game-box-loading">Loading box score…</div>';if(d.error)return'<div class="game-box-loading">Box score is temporarily unavailable.</div>';const box=d.boxscore||{};return`<div class="game-box">${gameTeamStats(box,a,h)}<div class="game-player-boxes">${boxPlayerCategories(box,a)}${boxPlayerCategories(box,h)}</div></div>`}
function live(){const cards=st.games.map(e=>{const c=e.competitions?.[0]||{},ts=c.competitors||[],a=ts.find(x=>x.homeAway==='away')||{},h=ts.find(x=>x.homeAway==='home')||{},key=String(e.id),open=st.gameOpen.has(key),status=e.status?.type?.shortDetail||c.status?.type?.shortDetail||'Scheduled';return`<div class="card game-card ${open?'game-open':''}"><div class="game-status-row"><div class="game-status">${esc(status)}</div><div class="muted small">${esc(c.venue?.fullName||'')}</div></div><div class="game-score-team"><div>${gameTeamLogo(a)?`<img src="${gameTeamLogo(a)}" alt="">`:''}<span><strong>${esc(a.team?.abbreviation||'Away')}</strong><small>${esc(a.team?.displayName||'')}</small></span></div><strong>${esc(a.score||'0')}</strong></div><div class="game-score-team"><div>${gameTeamLogo(h)?`<img src="${gameTeamLogo(h)}" alt="">`:''}<span><strong>${esc(h.team?.abbreviation||'Home')}</strong><small>${esc(h.team?.displayName||'')}</small></span></div><strong>${esc(h.score||'0')}</strong></div>${(a.linescores?.length||h.linescores?.length)?`<div class="period-score"><div></div><div class="period-score-row">${periodScore(a)}</div><div class="period-score-row">${periodScore(h)}</div></div>`:''}<button class="game-box-toggle" data-game-toggle="${esc(key)}">${open?'Hide box score':'View box score'} <span>${open?'⌃':'⌄'}</span></button>${gameBox(e,a,h)}</div>`}).join('');return layout('Live NFL Stats',`<div class="toolbar"><div><h1 class="page-title">Live NFL Stats</h1><p class="page-subtitle">Live scores, team box stats and passing/rushing/receiving lines. Expand any game for the full fantasy-relevant box score.</p></div><div style="margin-left:auto">${weekSel()}</div><button class="btn" data-a="refreshLive">Refresh</button></div>${cards?`<div class="scoreboard">${cards}</div>`:'<div class="empty">Loading current NFL games…</div>'}`)}
"""
if old_live not in s: raise SystemExit('live block missing')
s=s.replace(old_live,new_live,1)

old_bind='$\'(\'[data-a="refreshLive"]\')?.addEventListener(\'click\',liveLoad);'
# Avoid quote gymnastics: use exact normal text.
old_bind='$(\'[data-a="refreshLive"]\')?.addEventListener(\'click\',liveLoad);'
new_bind='$(\'[data-a="refreshLive"]\')?.addEventListener(\'click\',liveLoad);$$(`[data-game-toggle]`).forEach(x=>x.onclick=async()=>{const id=String(x.dataset.gameToggle);if(st.gameOpen.has(id)){st.gameOpen.delete(id);render();return}st.gameOpen.add(id);render();await loadGameDetails(id,true)});'
if old_bind not in s: raise SystemExit('bind live anchor missing')
s=s.replace(old_bind,new_bind,1)
MAIN.write_text(s,encoding='utf-8')

css=CSS.read_text(encoding='utf-8')
css += r'''

/* Web 1.3.5 — expandable live NFL box scores */
.game-card{overflow:hidden}.game-status-row{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:8px}.game-score-team{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:8px 0}.game-score-team>div{display:flex;align-items:center;gap:10px;min-width:0}.game-score-team img{width:34px;height:34px;object-fit:contain}.game-score-team span{display:grid;min-width:0}.game-score-team span strong{font-size:16px}.game-score-team span small{color:var(--muted);font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.game-score-team>strong{font-size:22px}.period-score{margin:8px 0 4px;border-top:1px solid var(--line);padding-top:8px}.period-score-row{display:flex;justify-content:flex-end;gap:6px;margin:3px 0}.period-score-row span{display:grid;place-items:center;min-width:34px;padding:4px 5px;border:1px solid rgba(36,51,43,.75);border-radius:7px;background:rgba(255,255,255,.015)}.period-score-row small{font-size:8px;color:var(--muted)}.period-score-row strong{font-size:11px}.game-box-toggle{width:100%;margin-top:10px;border:1px solid var(--line);background:rgba(182,255,69,.055);color:var(--accent);border-radius:10px;padding:9px 11px;font-weight:800;cursor:pointer;display:flex;justify-content:space-between}.game-box-loading{padding:18px 4px 4px;color:var(--muted);font-size:12px;text-align:center}.game-box{border-top:1px solid var(--line);margin:14px -15px -15px;padding:16px 15px;background:rgba(5,8,6,.28)}.game-section-title,.box-category-title{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);font-weight:850;margin-bottom:8px}.game-team-stats{border:1px solid var(--line);border-radius:11px;overflow:hidden;background:var(--panel)}.game-stat-head,.game-stat-row{display:grid;grid-template-columns:1fr 1.25fr 1fr;gap:8px;align-items:center;text-align:center;padding:7px 9px;border-bottom:1px solid rgba(36,51,43,.65)}.game-stat-head{background:#101713;color:var(--muted);font-size:9px;letter-spacing:.07em}.game-stat-row:last-child{border-bottom:0}.game-stat-row span{color:var(--muted);font-size:10px}.game-stat-row strong{font-size:12px}.game-player-boxes{display:grid;grid-template-columns:1fr;gap:14px;margin-top:16px}.game-team-box{min-width:0}.game-team-box-title{display:flex;align-items:center;gap:8px;margin-bottom:8px}.game-team-box-title img{width:26px;height:26px;object-fit:contain}.box-category{margin-top:10px}.box-table-wrap{overflow-x:auto;border:1px solid var(--line);border-radius:10px}.box-table{min-width:620px;font-size:11px}.box-table th,.box-table td{padding:7px 8px;white-space:nowrap}.box-table th:first-child,.box-table td:first-child{position:sticky;left:0;background:#101713;z-index:1;text-align:left}.box-table td:first-child{background:var(--panel)}
@media(min-width:1150px){.scoreboard{grid-template-columns:repeat(2,minmax(0,1fr))}.game-card.game-open{grid-column:span 2}.game-player-boxes{grid-template-columns:1fr 1fr}}
@media(max-width:600px){.scoreboard{grid-template-columns:1fr}.game-card{padding:13px}.game-box{margin:14px -13px -13px;padding:14px 13px}.game-score-team span small{max-width:190px}.box-table{min-width:560px}}
'''
CSS.write_text(css,encoding='utf-8')

p=PKG.read_text(encoding='utf-8')
if '"version": "1.3.4"' not in p: raise SystemExit('expected Web 1.3.4')
p=p.replace('"version": "1.3.4"','"version": "1.3.5"',1)
PKG.write_text(p,encoding='utf-8')
print('Patched Web 1.3.5: expandable NFL team/player box scores')
