from pathlib import Path

main = Path('web/src/main.js')
pkg = Path('web/package.json')
s = main.read_text(encoding='utf-8')

old_av = "function availabilityInfo(id,p=st.players?.[id],week=st.week,snapshotFactor=1){const rosterStatus=String(p?.status||'').trim(),injuryStatus=String(p?.injury_status||'').trim(),body=String(p?.injury_body_part||'').trim(),notes=String(p?.injury_notes||'').trim(),rs=rosterStatus.toLowerCase(),is=injuryStatus.toLowerCase(),hardRoster=/(^|\\b)(ir|pup|nfi|sus)($|\\b)|injured reserve|physically unable|non.?football injury|suspended/.test(rs),hardInjury=/^out$/.test(is),current=+week===+st.nflWeek,snapshotZero=n(snapshotFactor,1)<=0,forceZero=snapshotZero||(current&&(hardRoster||hardInjury)),factor=forceZero?0:Math.max(0,Math.min(1,n(snapshotFactor,1))),label=injuryStatus||(!/^active$/i.test(rosterStatus)?rosterStatus:'')||'',reason=snapshotZero?'Fantasy Model availability factor is 0 for this player-week.':current&&hardRoster?`${rosterStatus||'Unavailable'} from fresh Sleeper roster status.`:current&&hardInjury?`Sleeper lists the player Out for the current NFL week.`:factor<1?`Fantasy Model availability factor ${Math.round(factor*100)}% is already applied to the weekly forecast.`:label?`${label} is being monitored; no additional numeric override is applied unless availability becomes definitive.`:'No current availability restriction detected.';return{factor,forceZero,label,rosterStatus,injuryStatus,body,notes,reason,currentWeek:current}}"
new_av = "function availabilityInfo(id,p=st.players?.[id],week=st.week,snapshotFactor=1){const rosterStatus=String(p?.status||'').trim(),injuryStatus=String(p?.injury_status||'').trim(),body=String(p?.injury_body_part||'').trim(),notes=String(p?.injury_notes||'').trim(),rs=rosterStatus.toLowerCase(),is=injuryStatus.toLowerCase(),hardRoster=/(^|\\b)(ir|pup|nfi|sus|inactive)($|\\b)|injured reserve|physically unable|non.?football injury|suspended/.test(rs),hardInjury=/(^|\\b)(ir|out|pup|nfi|sus|inactive)($|\\b)|injured reserve|physically unable|non.?football injury|suspended/.test(is),definitive=hardRoster||hardInjury,nflWeek=Math.max(1,+st.nflWeek||1),currentOrFuture=+week>=nflWeek,snapshotZero=n(snapshotFactor,1)<=0,forceZero=snapshotZero||(currentOrFuture&&definitive),factor=forceZero?0:Math.max(0,Math.min(1,n(snapshotFactor,1))),label=injuryStatus||(!/^active$/i.test(rosterStatus)?rosterStatus:'')||'',reason=snapshotZero?'Fantasy Model availability factor is 0 for this player-week.':currentOrFuture&&definitive?`Sleeper lists this player as ${injuryStatus||rosterStatus||'unavailable'}; unplayed weekly projections are forced to 0 until that definitive status clears.`:factor<1?`Fantasy Model availability factor ${Math.round(factor*100)}% is already applied to the weekly forecast.`:label?`${label} is being monitored; no additional numeric override is applied unless availability becomes definitive.`:'No current availability restriction detected.';return{factor,forceZero,label,rosterStatus,injuryStatus,body,notes,reason,currentWeek:+week===nflWeek,definitive}}"
if old_av not in s:
    raise SystemExit('availabilityInfo source block not found')
s = s.replace(old_av, new_av, 1)

old_news = "async function loadPlayerNews(id,force=false){const key=String(id),cached=st.playerNews.get(key);if(!force&&cached&&Date.now()-n(cached.at,0)<10*60*1000)return cached;const p=st.players?.[id]||{},espnId=p?.espn_id;if(!espnId){const z={at:Date.now(),articles:[],source:'ESPN',unavailable:true};st.playerNews.set(key,z);return z}st.playerNews.set(key,{at:Date.now(),loading:true,articles:[],source:'ESPN'});if(String(st.profile)===key)render();const data=await liveJson(`https://site.api.espn.com/apis/site/v2/sports/football/nfl/athletes/${encodeURIComponent(espnId)}/news?limit=6`,null),articles=Array.isArray(data?.articles)?data.articles.slice(0,6).map(a=>({headline:a?.headline||a?.title||'Player update',description:a?.description||a?.story||'',published:a?.published||a?.lastModified||'',url:a?.links?.web?.href||a?.link?.href||''})):[];const z={at:Date.now(),articles,source:'ESPN',unavailable:!data};st.playerNews.set(key,z);if(String(st.profile)===key)render();return z}"
new_news = "async function loadPlayerNews(id,force=false){const key=String(id),cached=st.playerNews.get(key);if(!force&&cached&&Date.now()-n(cached.at,0)<10*60*1000)return cached;const p=st.players?.[id]||{},entry=resolveModel(id,p),base=entry?.base||{},espnId=p?.espn_id||field(base,['espn_id','espn_player_id','espnId']);st.playerNews.set(key,{at:Date.now(),loading:true,articles:[],source:'ESPN Fantasy'});if(String(st.profile)===key)render();let articles=[],ok=false;if(espnId){const data=await liveJson(`https://site.api.espn.com/apis/fantasy/v2/games/ffl/news/players?limit=20&playerId=${encodeURIComponent(espnId)}`,null);ok=!!data;const feed=Array.isArray(data?.feed)?data.feed:[];articles=feed.slice(0,6).map(a=>({headline:a?.headline||a?.title||'Player update',description:a?.description||a?.story||a?.summary||'',published:a?.published||a?.lastModified||a?.date||'',url:a?.links?.web?.href||a?.link?.href||a?.url||''})).filter(a=>a.headline)}if(!articles.length){const data=await liveJson('https://site.api.espn.com/apis/site/v2/sports/football/nfl/news?limit=100',null);ok=ok||!!data;const needle=normName(pname(id));articles=(Array.isArray(data?.articles)?data.articles:[]).filter(a=>normName(`${a?.headline||a?.title||''} ${a?.description||a?.story||''}`).includes(needle)).slice(0,6).map(a=>({headline:a?.headline||a?.title||'Player update',description:a?.description||a?.story||'',published:a?.published||a?.lastModified||'',url:a?.links?.web?.href||a?.link?.href||a?.url||''}))}const z={at:Date.now(),articles,source:'ESPN Fantasy',unavailable:!ok};st.playerNews.set(key,z);if(String(st.profile)===key)render();return z}"
if old_news not in s:
    raise SystemExit('loadPlayerNews source block not found')
s = s.replace(old_news, new_news, 1)

main.write_text(s, encoding='utf-8')

p = pkg.read_text(encoding='utf-8')
if '"version": "1.3.2"' not in p:
    raise SystemExit('expected Web 1.3.2 package version')
p = p.replace('"version": "1.3.2"', '"version": "1.3.3"', 1)
pkg.write_text(p, encoding='utf-8')

print('Patched Web 1.3.3: definitive IR override + ESPN fantasy news feed/fallback')
