import './styles.css';

const S='https://api.sleeper.app/v1', ESPN='https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard';
const st={route:localStorage.fm_route||'dashboard',tab:localStorage.fm_league_tab||'home',nav:false,username:localStorage.fm_username||'',season:+(localStorage.fm_season||new Date().getFullYear()),user:null,leagues:[],league:null,users:[],rosters:[],matchups:[],picks:[],drafts:[],players:null,week:null,team:null,snapshot:{},rows:[],modelById:new Map,modelByName:new Map,pickValues:new Map,games:[],tradeA:null,tradeB:null,assetsA:new Set,assetsB:new Set,compare:[],loading:false,error:''};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)], esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])), n=(v,f=null)=>Number.isFinite(Number(v))?Number(v):f, f=(v,d=1)=>n(v)==null?'—':Number(v).toFixed(d), fi=v=>n(v)==null?'—':Math.round(Number(v)).toLocaleString();
async function json(url,fallback=null){try{const r=await fetch(url,{headers:{accept:'application/json'}});if(!r.ok)throw Error(r.status);return await r.json()}catch(e){console.warn(url,e);return fallback}}
async function liveJson(url,fallback=null){try{const sep=url.includes('?')?'&':'?';const r=await fetch(`${url}${sep}_fm=${Date.now()}`,{headers:{accept:'application/json'},cache:'no-store'});if(!r.ok)throw Error(r.status);return await r.json()}catch(e){console.warn(url,e);return fallback}}
function toast(m){$('.toast')?.remove();const x=document.createElement('div');x.className='toast';x.textContent=m;document.body.append(x);setTimeout(()=>x.remove(),3500)}
function field(r,keys){if(!r)return null;for(const q of keys){const k=Object.keys(r).find(x=>x.toLowerCase()===q.toLowerCase());if(k&&r[k]!=null&&r[k]!=='')return r[k]}return null}
function normName(v){return String(v??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[.’']/g,'').replace(/[-_]/g,' ').replace(/\b(jr|sr|ii|iii|iv|v)\b/g,'').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ')}
function addName(k,e){if(!k)return;const a=st.modelByName.get(k)||[];if(!a.includes(e))a.push(e);st.modelByName.set(k,a)}
function buildModelIndex(s){st.modelById=new Map;st.modelByName=new Map;st.pickValues=new Map;const ps=Array.isArray(s?.players)?s.players:Object.values(s?.players||{});st.rows=ps;for(const base of ps){if(!base||typeof base!=='object')continue;const weeks=new Map;for(const w of Array.isArray(base.weekly_projections)?base.weekly_projections:[]){const wk=n(field(w,['week','game_week','target_week']));if(wk!=null)weeks.set(+wk,w)}const e={base,weeks};for(const v of [base.sleeper_id,base.sleeper_player_id,base.player_id,base.gsis_id])if(v!=null&&v!=='')st.modelById.set(String(v),e);for(const v of [base.player_name,base.full_name,base.name])addName(normName(v),e)}for(const r of Array.isArray(s?.pick_values)?s.pick_values:[]){const y=n(field(r,['season','pick_year','year'])),rd=n(field(r,['round','pick_round'])),v=n(field(r,['dynasty_value','value','asset_value','pick_value']));if(y!=null&&rd!=null&&v!=null)st.pickValues.set(`${y}:${rd}`,v)}}
function resolveModel(id,p){for(const v of [id,p?.sleeper_id,p?.player_id,p?.gsis_id]){if(v!=null&&v!==''&&st.modelById.has(String(v)))return st.modelById.get(String(v))}const name=normName(p?.full_name||[p?.first_name,p?.last_name].filter(Boolean).join(' '));const c=st.modelByName.get(name)||[];if(c.length<=1)return c[0]||null;const pos=String(p?.position||'').toUpperCase(),team=String(p?.team||'').toUpperCase();return c.find(x=>String(field(x.base,['position'])||'').toUpperCase()===pos&&String(field(x.base,['team'])||'').toUpperCase()===team)||c.find(x=>String(field(x.base,['position'])||'').toUpperCase()===pos)||c[0]}
async function snapshot(){st.snapshot=await json('/data/model_snapshot.json',{})||{};buildModelIndex(st.snapshot)}
function model(id,p=st.players?.[id],week=st.week){const e=resolveModel(id,p),base=e?.base||null,w=e?.weeks?.get(+week)||null,current=+st.snapshot?.projection_week===+week;const weekField=keys=>field(w,keys)??(current?field(base,keys):null);return{projection:n(weekField(['live_projection','current_projection','projected_points','projection','proj_fpts','fpts_proj','pred','prediction','mean','weekly_projection'])),pregame:n(weekField(['pregame_projection','original_projection','base_projection','neutral_projection','projected_points','projection'])),floor:n(weekField(['floor','projection_floor','p10','lower','lower_bound'])),ceiling:n(weekField(['ceiling','projection_ceiling','p90','upper','upper_bound'])),avg:n(field(w,['avg_ppg','ppg','fantasy_ppg','season_ppg','current_avg_ppg'])??field(base,['avg_ppg','ppg','fantasy_ppg','season_ppg','current_avg_ppg'])),dynasty:n(field(base,['dynasty_value','dynasty','asset_value','value','dynasty_score'])??field(w,['dynasty_value','dynasty','asset_value','value','dynasty_score'])),confidence:weekField(['confidence','projection_confidence','conf','confidence_score']),opp:weekField(['opponent','opp','opponent_team','opp_team']),matched:!!e,hasWeek:!!w}}
function auditProjections(){if(!st.rosters?.length||!st.players)return;const ids=[...new Set(st.rosters.flatMap(r=>r.players||[]))].filter(id=>['QB','RB','WR','TE'].includes(String(st.players?.[id]?.position||'').toUpperCase())),unmatched=[],missing=[];for(const id of ids){const m=model(id,st.players[id]);if(!m.matched)unmatched.push(pname(id));else if(m.projection==null)missing.push(pname(id))}console.info('[Fantasy Model] projection coverage',{week:st.week,total:ids.length,projected:ids.length-unmatched.length-missing.length,unmatched,missing})}
async function nflState(){const x=await json(`${S}/state/nfl`,{});if(!st.week)st.week=+(x?.week||1);if(!st.season)st.season=+(x?.season||new Date().getFullYear());return x}
async function players(){if(st.players)return;try{const c=localStorage.fm_players_cache,t=+localStorage.fm_players_cache_at;if(c&&Date.now()-t<64800000){st.players=JSON.parse(c);return}}catch{}st.players=await json(`${S}/players/nfl`,{})||{};try{localStorage.fm_players_cache=JSON.stringify(st.players);localStorage.fm_players_cache_at=Date.now()}catch{}}
function pname(id){const p=st.players?.[id];return p?.full_name||[p?.first_name,p?.last_name].filter(Boolean).join(' ')||`Player ${id}`}
function rby(id){return st.rosters.find(r=>+r.roster_id===+id)}
function me(){return st.rosters.find(r=>String(r.owner_id)===String(st.user?.user_id))}
function tname(id){const r=rby(id),u=st.users.find(u=>String(u.user_id)===String(r?.owner_id));return u?.metadata?.team_name||u?.display_name||`Team ${id}`}
function icon(l){return l?.avatar?`https://sleepercdn.com/avatars/thumbs/${encodeURIComponent(l.avatar)}`:''}
function head(id){return `https://sleepercdn.com/content/nfl/players/${encodeURIComponent(id)}.jpg`}
async function loadLeagues(user=st.username,season=st.season){st.loading=true;render();const u=await liveJson(`${S}/user/${encodeURIComponent(user)}`);if(!u?.user_id){st.loading=false;st.error='Sleeper user not found.';render();return}st.user=u;st.leagues=await liveJson(`${S}/user/${u.user_id}/leagues/nfl/${season}`,[])||[];st.username=user;st.season=+season;st.error='';localStorage.fm_username=user;localStorage.fm_season=season;st.loading=false;render()}
async function refreshLeague(notify=true){const id=st.league?.league_id;if(!id)return;st.loading=true;render();await Promise.all([players(),nflState()]);const [league,users,rosters,matchups,picks,drafts]=await Promise.all([liveJson(`${S}/league/${id}`,st.league),liveJson(`${S}/league/${id}/users`,[]),liveJson(`${S}/league/${id}/rosters`,[]),liveJson(`${S}/league/${id}/matchups/${st.week}`,[]),liveJson(`${S}/league/${id}/traded_picks`,[]),liveJson(`${S}/league/${id}/drafts`,[])]);if(league)st.league=league;st.users=users||[];st.rosters=rosters||[];st.matchups=matchups||[];st.picks=picks||[];st.drafts=drafts||[];st.team=rby(st.team)?.roster_id||me()?.roster_id||st.rosters[0]?.roster_id;st.tradeA=rby(st.tradeA)?.roster_id||me()?.roster_id||st.rosters[0]?.roster_id;st.tradeB=rby(st.tradeB)?.roster_id||st.rosters.find(r=>r.roster_id!==st.tradeA)?.roster_id;st.assetsA=new Set;st.assetsB=new Set;st.loading=false;auditProjections();render();if(notify)toast('League refreshed from Sleeper.')}
async function openLeague(id){st.league=st.leagues.find(l=>String(l.league_id)===String(id))||await liveJson(`${S}/league/${id}`);if(!st.league)return toast('Could not load league.');st.tab='home';localStorage.fm_league_id=id;localStorage.fm_league_tab='home';await refreshLeague(false)}
async function setWeek(w){st.week=+w;if(st.league)st.matchups=await liveJson(`${S}/league/${st.league.league_id}/matchups/${w}`,[])||[];auditProjections();render()}
function slots(){return(st.league?.roster_positions||[]).filter(s=>!['BN','IR','TAXI'].includes(String(s).toUpperCase()))}
function eligible(slot,p){const s=String(slot).toUpperCase(),pos=String(p?.position||'').toUpperCase();if(s===pos)return true;if(['FLEX','RB_WR_TE','WRRB_FLEX','REC_FLEX'].includes(s))return['RB','WR','TE'].includes(pos);if(['SUPER_FLEX','SUPERFLEX','OP'].includes(s))return['QB','RB','WR','TE'].includes(pos);if(s==='WR_TE')return['WR','TE'].includes(pos);return false}
function optimal(r){const ids=(r?.players||[]).filter(id=>st.players?.[id]),ss=[...slots()].sort((a,b)=>/FLEX|OP/.test(a)-/FLEX|OP/.test(b)),used=new Set,map=new Map;for(const s of ss){const c=ids.filter(id=>!used.has(id)&&eligible(s,st.players[id])).map(id=>({id,v:model(id).projection??-999})).sort((a,b)=>b.v-a.v)[0];if(c){used.add(c.id);map.set(c.id,s)}}return map}
function mi(id){return st.matchups.find(m=>+m.roster_id===+id)}
function oppId(id){const a=mi(id);return st.matchups.find(m=>m.matchup_id===a?.matchup_id&&+m.roster_id!==+id)?.roster_id}
function rproj(r){let total=0,ok=false;for(const id of optimal(r).keys()){const v=model(id).projection;if(v!=null){total+=v;ok=true}}return ok?total:null}
function ppg(r){const s=r?.settings||{},pts=n(s.fpts,0)+n(s.fpts_decimal,0)/100,g=n(s.wins,0)+n(s.losses,0)+n(s.ties,0);return g?pts/g:null}
function age(id){return n(st.players?.[id]?.age)}
function avgAge(r){const a=(r?.players||[]).map(age).filter(x=>x!=null);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
function dval(id){return model(id).dynasty||0}
function rdyn(r){return(r?.players||[]).reduce((a,id)=>a+dval(id),0)}
function strength(r){const x={QB:[],RB:[],WR:[],TE:[]};for(const id of r?.players||[]){const p=st.players?.[id];if(x[p?.position])x[p.position].push(model(id).projection||0)};Object.values(x).forEach(a=>a.sort((a,b)=>b-a));return{QB:x.QB[0]||0,RB:(x.RB[0]||0)+(x.RB[1]||0),WR:(x.WR[0]||0)+(x.WR[1]||0)+(x.WR[2]||0),TE:x.TE[0]||0}}
function need(r){const s=strength(r),avg={};for(const p of Object.keys(s))avg[p]=st.rosters.reduce((a,x)=>a+strength(x)[p],0)/(st.rosters.length||1);return Object.keys(s).sort((a,b)=>s[a]/(avg[a]||1)-s[b]/(avg[b]||1))[0]||'—'}
function windowOf(r){const a=avgAge(r),v=ppg(r),all=st.rosters.map(ppg).filter(x=>x!=null).sort((a,b)=>a-b),med=all[Math.floor(all.length/2)];if(v!=null&&med!=null&&v>=med&&(a==null||a<28))return'Contender';if(a!=null&&a<25.5&&(v==null||med==null||v<med))return'Rebuilding';return'Fringe'}
function draftComplete(y=st.season){return st.drafts.some(d=>+d.season===+y&&String(d.status||'').toLowerCase()==='complete')}
function pickAssets(id){const rounds=+(st.league?.settings?.draft_rounds||4),out=[],first=draftComplete(st.season)?st.season+1:st.season;for(let y=first;y<=st.season+3;y++)for(let r=1;r<=rounds;r++){let owner=id;const t=[...st.picks].reverse().find(p=>+p.roster_id===+id&&+p.season===y&&+p.round===r);if(t?.owner_id)owner=t.owner_id;if(+owner===+id)out.push({season:y,round:r,original:id,key:`pick:${y}:${r}:${id}`})}for(const p of st.picks)if(+p.owner_id===+id&&+p.roster_id!==+id&&+p.season>=first){const q={season:+p.season,round:+p.round,original:+p.roster_id,key:`pick:${p.season}:${p.round}:${p.roster_id}`};if(!out.some(x=>x.key===q.key))out.push(q)}return out.sort((a,b)=>a.season-b.season||a.round-b.round)}
function pickVal(p){const v=st.pickValues.get(`${+p.season}:${+p.round}`);if(v!=null)return v;return Math.round(({1:4200,2:1800,3:800,4:350}[p.round]||100)*Math.pow(.92,Math.max(0,p.season-st.season-1)))}
const ord=r=>({1:'1st',2:'2nd',3:'3rd'}[r]||`${r}th`), conf=v=>v==null?'—':isNaN(+v)?String(v):(+v<=1?+v:+v/100)>=.75?'High':(+v<=1?+v:+v/100)>=.5?'Med':'Low';
function nav(route,i,label){return`<button class="nav-btn ${st.route===route?'active':''}" data-route="${route}"><span class="nav-icon">${i}</span><span class="nav-label">${label}</span></button>`}
function layout(title,body){return`<div class="shell ${st.nav?'nav-open':''}"><aside class="sidebar"><div class="brand"><div class="brand-mark">FM</div><div class="brand-copy">Fantasy Model</div></div><button class="nav-toggle" data-a="nav">${st.nav?'← Collapse':'→'}</button><nav class="nav-list">${nav('dashboard','▦','Dashboard')}${nav('live','◉','Live NFL Stats')}${nav('leaders','≡','NFL Leaders')}${nav('startsit','⚖','Start/Sit Tool')}<hr class="nav-separator">${nav('about','ⓘ','About')}</nav></aside><main class="main"><header class="topbar"><div><h1>${esc(title)}</h1><div class="crumb">${st.league?`${esc(st.league.name)} · ${esc(tname(me()?.roster_id))}`:'Fantasy Model'}</div></div><div class="top-actions">${st.league?'<button class="btn btn-ghost" data-a="refreshLeague">Refresh league</button><button class="btn btn-ghost" data-a="back">All leagues</button>':''}<span class="pill">${st.season} season</span></div></header><div class="content">${body}</div></main></div>`}
function tabs(){return`<div class="league-tabs">${[['home','Home'],['teams','Teams'],['league','League'],['trade','Trade Center'],['moves','Recommended Moves']].map(([a,b])=>`<button class="league-tab ${st.tab===a?'active':''}" data-tab="${a}">${b}</button>`).join('')}</div>`}
function weekSel(){return`<select class="select" data-a="week">${Array.from({length:18},(_,i)=>i+1).map(w=>`<option value="${w}" ${w===st.week?'selected':''}>Week ${w}</option>`).join('')}</select>`}
function dashboard(){if(st.league)return leagueShell();const cards=st.leagues.map(l=>`<div class="card league-card" data-league="${esc(l.league_id)}"><div style="display:flex;gap:12px;align-items:center">${icon(l)?`<img class="league-avatar" src="${icon(l)}" alt="">`:`<div class="league-avatar" style="display:grid;place-items:center;font-weight:900">${esc((l.name||'L')[0])}</div>`}<div><div class="eyebrow">${l.settings?.type===2?'Dynasty':'Fantasy'} league</div><div style="font-size:18px;font-weight:850">${esc(l.name)}</div><div class="muted small">${esc(l.total_rosters||'')} teams · ${esc(l.season)}</div></div></div></div>`).join('');return layout('Dashboard',`<h1 class="page-title">Dashboard</h1><p class="page-subtitle">Connect your Sleeper account, load a season, then enter any league.</p><div class="card card-pad"><div class="form-row"><label><span>Sleeper username</span><input id="username" class="input" value="${esc(st.username)}"></label><label><span>Season</span><input id="season" class="input" type="number" value="${st.season}"></label><button class="btn btn-primary" data-a="load">${st.loading?'Loading…':'Load leagues'}</button></div>${st.error?`<p style="color:var(--bad)">${esc(st.error)}</p>`:''}</div>${cards?`<div class="section-head"><h2>Your leagues</h2></div><div class="league-cards">${cards}</div>`:'<div class="empty" style="margin-top:18px">Load your Sleeper leagues to begin.</div>'}`)}
function matchup(r){const o=rby(oppId(r.roster_id)),la=n(mi(r.roster_id)?.points,0),lb=n(mi(o?.roster_id)?.points,0),live=la>0||lb>0;return`<div class="card matchup-card"><div class="eyebrow">Week ${st.week} matchup</div>${o?`<div class="matchup-main"><div class="matchup-team"><strong>${esc(tname(r.roster_id))}</strong><div class="matchup-score">${live?f(la):f(rproj(r))}</div><div class="matchup-proj">${live?`Current final projection ${f(rproj(r))}`:'Pregame projection'}</div></div><div class="vs">VS</div><div class="matchup-team right"><strong>${esc(tname(o.roster_id))}</strong><div class="matchup-score">${live?f(lb):f(rproj(o))}</div><div class="matchup-proj">${live?`Current final projection ${f(rproj(o))}`:'Pregame projection'}</div></div></div>`:'<div class="empty" style="margin-top:10px">No opponent scheduled this week.</div>'}</div>`}
function rosterTable(r,ids,opt){return ids.length?`<div class="roster-table-wrap"><table><thead><tr><th>Player</th><th>Projection</th><th>Live Fantasy</th><th>Floor</th><th>Ceiling</th><th>Avg PPG</th><th>Dynasty</th><th>Lineup</th><th>Confidence</th></tr></thead><tbody>${ids.map(id=>{const p=st.players?.[id]||{},m=model(id,p),live=n(mi(r.roster_id)?.players_points?.[id],0),slot=opt.get(id),opp=m.opp||'Matchup unavailable',jersey=p.number||p.jersey_number;return`<tr><td><div class="player-cell"><img class="player-headshot" src="${head(id)}" alt="" onerror="this.style.visibility='hidden'"><div><div class="player-name">${esc(pname(id))}</div><div class="player-meta">${esc(p.position||'—')} · ${esc(p.team||'FA')}${jersey?` · #${esc(jersey)}`:''}</div><div class="player-opp">${esc(opp)}</div></div></div></td><td><strong>${f(m.projection)}</strong></td><td>${f(live)}</td><td>${f(m.floor)}</td><td>${f(m.ceiling)}</td><td>${f(m.avg)}</td><td>${m.dynasty!=null?fi(m.dynasty):'—'}</td><td>${slot?`<span class="slot-label">START · ${esc(slot)}</span>`:'<span class="slot-label sit">SIT</span>'}</td><td>${esc(conf(m.confidence))}</td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">No players found.</div>'}
function picks(r){const p=pickAssets(r.roster_id);return p.length?`<div class="pick-grid">${p.map(x=>`<div class="pick"><strong>${x.season} ${ord(x.round)}</strong><div class="muted small">${x.original===r.roster_id?'Own pick':`via ${esc(tname(x.original))}`}</div><div class="small" style="color:var(--accent);margin-top:5px">Value ${fi(pickVal(x))}</div></div>`).join('')}</div>`:'<div class="empty">No future picks found.</div>'}
function teamHome(r,own=true){if(!r)return'<div class="empty">No roster found for this user.</div>';const opt=optimal(r),starts=(r.starters||[]).filter(x=>x&&x!=='0'),set=new Set(starts),bench=(r.players||[]).filter(x=>!set.has(x));return`<div class="toolbar"><div><div class="eyebrow">${own?'Your team':'Team view'}</div><h1 class="page-title">${esc(tname(r.roster_id))}</h1></div><div style="margin-left:auto">${weekSel()}</div></div>${matchup(r)}<div class="section-head"><h2>Starters</h2><span class="muted small">Model lineup indicators use league roster slots</span></div>${rosterTable(r,starts,opt)}<div class="section-head"><h2>Bench</h2></div>${rosterTable(r,bench,opt)}<div class="section-head"><h2>Draft Picks</h2></div>${picks(r)}`}
function teams(){const r=rby(st.team)||st.rosters[0];return`<div class="toolbar"><select class="select" data-a="team">${st.rosters.map(x=>`<option value="${x.roster_id}" ${x.roster_id===r?.roster_id?'selected':''}>${esc(tname(x.roster_id))}</option>`).join('')}</select></div>${teamHome(r,false)}`}
function leagueOverview(){const ranks=[...st.rosters].sort((a,b)=>(ppg(b)||0)*10+rdyn(b)/100+(rproj(b)||0)*3-((ppg(a)||0)*10+rdyn(a)/100+(rproj(a)||0)*3)),stand=[...st.rosters].sort((a,b)=>n(b.settings?.wins,0)-n(a.settings?.wins,0)||((n(b.settings?.fpts,0)+n(b.settings?.fpts_decimal,0)/100)-(n(a.settings?.fpts,0)+n(a.settings?.fpts_decimal,0)/100))),po=+(st.league?.settings?.playoff_teams||6);return`<div class="toolbar"><div><div class="eyebrow">League overview</div><h1 class="page-title">${esc(st.league.name)}</h1></div><div style="margin-left:auto">${weekSel()}</div></div><div class="table-wrap"><table><thead><tr><th>Rank</th><th>Team</th><th>Window</th><th>Dynasty Value</th><th>Week Projection</th><th>Avg PPG</th><th>Avg. Age</th><th>Biggest Need</th></tr></thead><tbody>${ranks.map((r,i)=>`<tr><td><strong>#${i+1}</strong></td><td style="text-align:left"><strong>${esc(tname(r.roster_id))}</strong></td><td>${windowOf(r)}</td><td>${fi(rdyn(r))}</td><td>${f(rproj(r))}</td><td>${f(ppg(r))}</td><td>${f(avgAge(r))}</td><td><span class="pill warn">${need(r)}</span></td></tr>`).join('')}</tbody></table></div><div class="section-head"><h2>Current Playoff Picture</h2><span class="muted small">${po} playoff spots</span></div>${stand.map((r,i)=>{const s=r.settings||{},pts=n(s.fpts,0)+n(s.fpts_decimal,0)/100,status=i<po?'In playoff position':i===po?'On the bubble':'Outside looking in';return`<div class="standing-row"><strong>#${i+1}</strong><div><strong>${esc(tname(r.roster_id))}</strong><div class="muted small">${n(s.wins,0)}-${n(s.losses,0)}</div></div><strong>${f(pts)}</strong><span class="muted small">Points for</span><span class="pill ${i<po?'good':i===po?'warn':''}">${status}</span></div>`}).join('')}`}
function aval(k){if(k.startsWith('player:'))return dval(k.slice(7));const[,y,r,o]=k.split(':');return pickVal({season:+y,round:+r,original:+o})}function total(s){return[...s].reduce((a,k)=>a+aval(k),0)}
function assets(r,set,side){const ps=(r?.players||[]).map(id=>({k:`player:${id}`,l:pname(id),m:st.players?.[id]?.position||'',v:dval(id)})),pk=pickAssets(r?.roster_id).map(x=>({k:x.key,l:`${x.season} ${ord(x.round)}`,m:x.original===r.roster_id?'Own pick':`via ${tname(x.original)}`,v:pickVal(x)}));return`<div class="asset-list">${[...ps,...pk].map(a=>`<button class="asset ${set.has(a.k)?'selected':''}" data-side="${side}" data-asset="${esc(a.k)}"><span style="text-align:left"><strong>${esc(a.l)}</strong><span class="muted small" style="display:block">${esc(a.m)}</span></span><strong>${fi(a.v)}</strong></button>`).join('')}</div>`}
function recommendation(){const r=me();if(!r)return'';const nd=need(r),mine=(r.players||[]).map(id=>({id,v:dval(id),p:st.players?.[id]})).filter(x=>x.v>0);let best;for(const o of st.rosters.filter(x=>x.roster_id!==r.roster_id))for(const id of o.players||[]){const p=st.players?.[id],v=dval(id);if(p?.position!==nd||!v)continue;const g=mine.filter(x=>x.p?.position!==nd).sort((a,b)=>Math.abs(a.v-v)-Math.abs(b.v-v))[0];if(g&&(!best||Math.abs(g.v-v)<best.d))best={o,id,v,g,d:Math.abs(g.v-v)}}return best?`<div class="recommendation"><div class="rec-rank">TOP TRADE PATH</div><div class="rec-title">Target ${esc(pname(best.id))} from ${esc(tname(best.o.roster_id))}</div><p class="muted">Your largest modeled need is ${nd}. A value-balanced starting point is ${esc(pname(best.g.id))}; refine with draft capital in the simulator.</p><div class="grid grid-3"><div class="metric"><div class="metric-label">You send</div><div class="metric-value">${fi(best.g.v)}</div></div><div class="metric"><div class="metric-label">You receive</div><div class="metric-value">${fi(best.v)}</div></div><div class="metric"><div class="metric-label">Raw gap</div><div class="metric-value">${fi(best.g.v-best.v)}</div></div></div></div>`:`<div class="recommendation"><div class="rec-title">Improve ${nd}</div><p class="muted">No clean one-for-one target surfaced. Build a package below.</p></div>`}
function trade(){const a=rby(st.tradeA)||me()||st.rosters[0],b=rby(st.tradeB)||st.rosters.find(x=>x.roster_id!==a?.roster_id),ta=total(st.assetsA),tb=total(st.assetsB),gap=ta-tb,d=Math.abs(gap)/Math.max(ta,tb,1),bal=d<=.05?'Near even':d<=.15?'Moderate gap':'Large gap';const opts=r=>st.rosters.map(x=>`<option value="${x.roster_id}" ${x.roster_id===r?.roster_id?'selected':''}>${esc(tname(x.roster_id))}</option>`).join('');return`<div class="eyebrow">Trade Center</div><h1 class="page-title">Recommended trades + simulator</h1><p class="page-subtitle">Compare dynasty value, draft capital and roster fit. Balance is not an acceptance probability.</p><div class="section-head"><h2>Recommended</h2></div>${recommendation()}<div class="section-head"><h2>Trade Simulator</h2><span class="pill ${d<=.05?'good':d<=.15?'warn':'bad'}">${bal}</span></div><div class="trade-layout"><div class="card card-pad"><select class="select" data-a="tradeA">${opts(a)}</select><div style="height:12px"></div>${assets(a,st.assetsA,'a')}<div class="trade-total"><span>Total value</span><span>${fi(ta)}</span></div></div><div class="card card-pad"><select class="select" data-a="tradeB">${opts(b)}</select><div style="height:12px"></div>${assets(b,st.assetsB,'b')}<div class="trade-total"><span>Total value</span><span>${fi(tb)}</span></div></div></div><div class="grid grid-4" style="margin-top:14px"><div class="metric"><div class="metric-label">Value difference</div><div class="metric-value">${fi(gap)}</div></div><div class="metric"><div class="metric-label">Balance</div><div class="metric-value" style="font-size:18px">${bal}</div></div><div class="metric"><div class="metric-label">${esc(tname(a?.roster_id))} need</div><div class="metric-value">${need(a)}</div></div><div class="metric"><div class="metric-label">${esc(tname(b?.roster_id))} need</div><div class="metric-value">${need(b)}</div></div></div><p class="muted small">Pick values use model snapshot values when available and a baseline future-pick curve otherwise. League trade-history calibration can be added later.</p>`}
function moves(){const r=me();if(!r)return'<div class="empty">Connect a roster first.</div>';const nd=need(r),opt=optimal(r),cur=new Set(r.starters||[]),swap=[...opt.entries()].find(([id])=>!cur.has(id)),sur=['QB','RB','WR','TE'].map(p=>({p,c:(r.players||[]).filter(id=>st.players?.[id]?.position===p).length})).sort((a,b)=>b.c-a.c)[0],recs=[[`Upgrade ${nd}`,`${nd} is your largest relative roster need.`,`Open Trade Center and target teams strong at ${nd}.`],...(swap?[[`Start ${pname(swap[0])}`,`The optimizer places this player in ${swap[1]}.`,'Review the Home tab before kickoff.']]:[]),[`Shop surplus ${sur?.p||'depth'}`,`You carry ${sur?.c||0} ${sur?.p||''} assets, your deepest raw position group.`,'Use depth to address need before spending premium picks.']];return`<div class="eyebrow">Recommended Moves</div><h1 class="page-title">What should you do next?</h1><p class="page-subtitle">Prioritized GM actions from your roster, league context, projections and dynasty values.</p><div class="grid">${recs.map((x,i)=>`<div class="recommendation"><div class="rec-rank">#${i+1}</div><div class="rec-title">${esc(x[0])}</div><p class="muted">${esc(x[1])}</p><strong>Best path</strong><p>${esc(x[2])}</p></div>`).join('')}</div>`}
function leagueShell(){let x=st.loading?'<div class="empty">Loading league…</div>':st.tab==='home'?teamHome(me()):st.tab==='teams'?teams():st.tab==='league'?leagueOverview():st.tab==='trade'?trade():moves();return layout(st.league.name,tabs()+x)}
async function liveLoad(){const ns=await nflState(),data=await json(`${ESPN}?dates=${ns?.season||st.season}&seasontype=2&week=${st.week}`,{});st.games=data?.events||[];render()}
function live(){const cards=st.games.map(e=>{const c=e.competitions?.[0]||{},ts=c.competitors||[],a=ts.find(x=>x.homeAway==='away')||{},h=ts.find(x=>x.homeAway==='home')||{};return`<div class="card game-card"><div class="game-status">${esc(e.status?.type?.shortDetail||'Scheduled')}</div><div class="game-line"><span>${esc(a.team?.abbreviation||'Away')}</span><span>${esc(a.score||'0')}</span></div><div class="game-line"><span>${esc(h.team?.abbreviation||'Home')}</span><span>${esc(h.score||'0')}</span></div><div class="muted small">${esc(c.venue?.fullName||'')}</div></div>`}).join('');return layout('Live NFL Stats',`<div class="toolbar"><div><h1 class="page-title">Live NFL Stats</h1><p class="page-subtitle">NFL scores and game status. No fantasy points.</p></div><div style="margin-left:auto">${weekSel()}</div><button class="btn" data-a="refreshLive">Refresh</button></div>${cards?`<div class="scoreboard">${cards}</div>`:'<div class="empty">Loading current NFL games…</div>'}`)}
function leader(title,keys){const a=st.rows.map(r=>({v:n(field(r,keys)),name:field(r,['player_name','full_name','name','player'])})).filter(x=>x.v!=null&&x.name).sort((a,b)=>b.v-a.v).slice(0,5);return`<div class="card card-pad"><div class="eyebrow">NFL leader</div><h3>${title}</h3>${a.length?a.map((x,i)=>`<div class="leader-row"><strong>${i+1}</strong><span>${esc(x.name)}</span><strong>${fi(x.v)}</strong></div>`).join(''):'<div class="empty">Not in current snapshot.</div>'}</div>`}
function leaders(){const c=[['Passing Yards',['passing_yards','pass_yards']],['Passing TDs',['passing_tds','pass_tds']],['Rushing Yards',['rushing_yards','rush_yards']],['Rushing TDs',['rushing_tds','rush_tds']],['Receiving Yards',['receiving_yards','rec_yards']],['Receptions',['receptions','rec']],['Receiving TDs',['receiving_tds','rec_tds']],['Targets',['targets']]];return layout('NFL Leaders',`<h1 class="page-title">NFL Leaders</h1><p class="page-subtitle">Top five real-NFL statistical leaders when those season totals are present in the production snapshot.</p><div class="leaders-grid">${c.map(x=>leader(x[0],x[1])).join('')}</div>`)}
function startsit(){const c=st.compare.map(id=>{const p=st.players?.[id]||{},m=model(id,p);return`<div class="metric"><div class="player-name">${esc(pname(id))}</div><div class="player-meta">${esc(p.position||'')} · ${esc(p.team||'FA')}</div><div class="metric-value">${f(m.projection)}</div><div class="muted small">Floor ${f(m.floor)} · ceiling ${f(m.ceiling)}</div><button class="btn btn-ghost" data-remove="${id}">Remove</button></div>`}).join('');return layout('Start/Sit Tool',`<h1 class="page-title">Start/Sit Tool</h1><p class="page-subtitle">Compare 2–4 players. League-specific recommended lineups live in Dashboard.</p><div class="card card-pad"><input id="search" class="input" placeholder="Search player…"><div id="results" class="asset-list" style="margin-top:9px"></div></div><div class="grid grid-4" style="margin-top:14px">${c||'<div class="empty">Add players to compare.</div>'}</div>`)}
function about(){const m=st.snapshot?.metadata||st.snapshot?.meta||{},v=m.version||m.model_version||st.snapshot?.version||'Production snapshot';return layout('About',`<h1 class="page-title">About Fantasy Model</h1><p class="page-subtitle">Fantasy Model combines weekly projections, uncertainty ranges, dynasty valuation, roster context and league-aware decision tools. Technical model details live here instead of normal fantasy pages.</p><div class="grid grid-3"><div class="metric"><div class="metric-label">Production</div><div class="metric-value" style="font-size:18px">${esc(v)}</div></div><div class="metric"><div class="metric-label">Model rows detected</div><div class="metric-value">${fi(st.rows.length)}</div></div><div class="metric"><div class="metric-label">League integration</div><div class="metric-value" style="font-size:18px">Sleeper</div></div></div>`)}
function render(){const html=st.route==='dashboard'?dashboard():st.route==='live'?live():st.route==='leaders'?leaders():st.route==='startsit'?startsit():about();$('#app').innerHTML=html;bind()}
function bind(){$$('[data-route]').forEach(x=>x.onclick=async()=>{st.route=x.dataset.route;localStorage.fm_route=st.route;render();if(st.route==='live'&&!st.games.length)liveLoad();if(st.route==='startsit')players()});$('[data-a="nav"]')?.addEventListener('click',()=>{st.nav=!st.nav;render()});$('[data-a="load"]')?.addEventListener('click',()=>loadLeagues($('#username').value.trim(),+$('#season').value));$$('[data-league]').forEach(x=>x.onclick=()=>openLeague(x.dataset.league));$('[data-a="refreshLeague"]')?.addEventListener('click',()=>refreshLeague(true));$('[data-a="back"]')?.addEventListener('click',()=>{st.league=null;localStorage.removeItem('fm_league_id');render()});$$('[data-tab]').forEach(x=>x.onclick=()=>{st.tab=x.dataset.tab;localStorage.fm_league_tab=st.tab;render()});$('[data-a="week"]')?.addEventListener('change',async e=>{await setWeek(+e.target.value);if(st.route==='live')liveLoad()});$('[data-a="team"]')?.addEventListener('change',e=>{st.team=+e.target.value;render()});$('[data-a="tradeA"]')?.addEventListener('change',e=>{st.tradeA=+e.target.value;st.assetsA=new Set;render()});$('[data-a="tradeB"]')?.addEventListener('change',e=>{st.tradeB=+e.target.value;st.assetsB=new Set;render()});$$('[data-side]').forEach(x=>x.onclick=()=>{const set=x.dataset.side==='a'?st.assetsA:st.assetsB;set.has(x.dataset.asset)?set.delete(x.dataset.asset):set.add(x.dataset.asset);render()});$('[data-a="refreshLive"]')?.addEventListener('click',liveLoad);const s=$('#search');if(s)s.oninput=()=>{const q=s.value.toLowerCase().trim(),found=!q||!st.players?[]:Object.entries(st.players).filter(([,p])=>String(p.full_name||'').toLowerCase().includes(q)&&['QB','RB','WR','TE'].includes(p.position)).slice(0,12),box=$('#results');box.innerHTML=found.map(([id,p])=>`<button class="asset" data-add="${id}"><span><strong>${esc(p.full_name)}</strong><span class="muted small" style="display:block">${esc(p.position)} · ${esc(p.team||'FA')}</span></span><span>+</span></button>`).join('');$$('[data-add]',box).forEach(x=>x.onclick=()=>{if(st.compare.length>=4)return toast('Compare up to four players.');if(!st.compare.includes(x.dataset.add))st.compare.push(x.dataset.add);render()})};$$('[data-remove]').forEach(x=>x.onclick=()=>{st.compare=st.compare.filter(id=>id!==x.dataset.remove);render()})}
async function init(){await Promise.all([snapshot(),nflState()]);render();if(st.username){await loadLeagues(st.username,st.season);const id=localStorage.fm_league_id;if(id&&st.leagues.some(l=>String(l.league_id)===id))await openLeague(id)}if(st.route==='live')liveLoad()}
init();
